### ISSUE TITLE
Are you implenting Graffiti?

### ISSUE THREAD

**Issue by DrAlta** [migueletto/PumpkinOS#13]
It was reverse engineered from the java demo they had on their web site.

[here's the reverse engineered JS version on the wayback machine](https://web.archive.org/web/20151002135316/http://home.comcast.net/~urbanjost/canvas/graffiti/Gestures.html)

but it only has the stroke information for the alphabet.  Can you tease of the rest of the strokes from the ROM?

**Comment by migueletto** [comment]
PumpkinOS has a Graffiti alternative. The implementation was based on this excellent article:
https://jackschaedler.github.io/handwriting-recognition/

It behaves much like Graffiti, but it is not a100% replacement. Here is a small demonstration:
https://www.youtube.com/watch?v=aegExwcIJgE

However, the standard PumpkinOS configuration is keyboard based, as there is no stroke recognition area. In order to use stroke recognition you have to enable DIA mode (that is Dynamic Input Area), which makes the PumpkinOS window mimic a PalmOS device form factor. Changing a single parameter in the script/pumpkin_linux.lua script (or script\pumpkin_windows.lua if on Windows) will do it:

Change:
pumpkin.start(1024, 680, 16, false, false, false, "Launcher")

To:
pumpkin.start(1024, 680, 16, false, true, false, "Launcher")

And restart PumpkinOS.

If you are interested in the implementation details, check the src/libpumpkin/grail.c source file.
